apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8deploy
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: k8-deploy-site
        image: ranschneider/k8deploy:v1
---
apiVersion: v1
kind: Service
metadata:
  name: k8deploy-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 30001